MODEL: resnet50
DOWNSTREAM_EVAL: finetune
DOWNSTREAM_DROP: 0.2
BATCH_SIZE: 32 
MAX_EPOCHS: 50
VAL_INTERVAL: 50
OPTIM: sgd 
WARMUP_EPOCHS: 0
MIXUP: 0.
CUTMIX: 0.
COLOR_JITTER: 0.
AUTO_AUGMENT: ''
SCHED: multistep
DECAY_EPOCHS: [25, 37]
LR: 0.001
WD: 0.
SMOOTHING: 0.
INTERPOLATION: bilinear
